language: java
language: android

jdk:
  - oraclejdk7
  - oraclejdk8

android:
  components:
    - tools
    - build-tools-25.0.2
    - android-25
    - platform-tools
    - extra-android-support
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

script:
  - ./gradlew check