language: android
jdk: oraclejdk8

android:
  components:
  - tools
  - tools
  - platform-tools
  - build-tools-27.0.3
  - android-28
  - extra
  - addon

  licenses:
    - 'android-sdk-license-.+'

before_install:
 - chmod +x gradlew

script:
  - ./gradlew :core:test

after_success:
 - ./gradlew cobertura coveralls

deploy:
 - provider: script
   script: ./gradlew bintrayUpload -PbintrayUser="${BINTRAY_USER}" -PbintrayKey="${BINTRAY_KEY}" -PdryRun=false
   skip_cleanup: true
   on:
     tags: true
