language: java
language: android

jdk:
  - oraclejdk7
  - oraclejdk8

android:
  components:
  - tools
  - tools
  - platform-tools
  - build-tools-25.0.1
  - android-25
  - extra
  - addon

script:
  - ./gradlew :core:check